#!/usr/bin/env ruby
require File.expand_path('../../config/environment',  __FILE__)
require 'optparse'

options = {}
 
optparse = OptionParser.new do|opts|

  opts.banner = "Usage: importer.rb [options]"
  
  options[:path] = ""
  opts.on( '-p', '--path PATH', 'Path to the Slideset') do |path|
    options[:path] = path
  end
  
  
  options[:slideset] = ""
  opts.on( '-s', '--slideset SLIDESET', 'Name of the Slideset') do |slideset|
    options[:slideset] = slideset
  end
  
  opts.on( '-h', '--help', 'Display this screen' ) do
    puts opts
    exit
  end
end
 
optparse.parse!


slideset = Slideset.create(  title: options[:slideset] )
slides = Dir["#{options[:path]}/*.*"]
slides.sort!

slides.each do|f|
  file = File.open(f)
  Slide.create(image: file, slideset: slideset)
end

def get_image_stream
 File.open("#{Rails.root}/spec/fixtures/folie-0001-256-w50k.png")
end


  
